version: 0.0
#extra12
os: linux
files:
  - source: codedeploy/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: codedeploy/scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: codedeploy/scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy/scripts/stop_server.sh
      timeout: 300
      runas: root