version: 0.0
os: linux
files:
  - source: /App
    destination: /var/www/html/DotNetWebApp
hooks:
  BeforeInstall:
  - location: scripts/install_dependencies.sh
    timeout: 300
    runas: root
  ApplicationStart:
     - location: scripts/start-server.sh
  ApplicationStop:
     - location: scripts/stop-server.sh
      timeout: 300
      runas: root