apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fhpl-cluster
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-0e72ca1fe1a4d36da }
      us-east-1b: { id: subnet-0a75bfd5be4652120 }

nodeGroups:
  - name: fhpl-ng-workers
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
  - name: fhpl-ng-builders
    labels: { role: builders }
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
