version: 0.0
#extra
os: linux
files:
  - source: codedeploy/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: codedeploy/scripts/install_dependencies
      timeout: 300
      runas: root
    - location: codedeploy/scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy/scripts/stop_server
      timeout: 300
      runas: root

